name: Print Version

on:
  push:
    branches:
      - feat/pipeline

jobs:
  print-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read bun version
        run: VERSION=$(grep 'version:' version.yml | awk '{print $2}')

      - name: Clone bun
        run: |
          # Clone the external repository with the specified tag
          git clone -b bun-$VERSION --depth 1 git@github.com:oven-sh/bun.git ./bun
          
          # Navigate to the cloned repository
          cd bun
          
          pwd
