name: Print Version

on:
  push:
    branches:
      - feat/pipeline

jobs:
  print-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read bun version
        run: |
          VERSION=$(grep 'version:' version.yml | awk '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Install bun
        run: |
          curl -fsSL https://bun.sh/install | bash -s -- bun-v$VERSION

      - name: Clone bun
        run: git clone -b bun-v$VERSION --depth 1 https://github.com/oven-sh/bun.git ./bun

      - name: Build layer
        run: |
          curl -fsSL https://bun.sh/install | bash -s -- bun-v$VERSION
          cd bun/packages/bun-lambda
          bun install
